### ISSUE TITLE
failed to activate the linter package

### ISSUE THREAD

**Issue by baddyz** [atom-community/linter#1013]
**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'interact.js'

Error: Cannot find module 'interact.js'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\n.dfg\AppData\Local\atom\app-1.2.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:/Users/n.sdf/.atom/packages/linter-master/lib/ui/bottom-panel.js:3:18)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (C:\Users\n.sdf\AppData\Local\atom\app-1.2.4\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.12
highlight-selected, v0.10.1
laravel, v0.7.0
linter, v1.11.3
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like Atom didn't fully install the latest version, can you try uninstalling it and re-installing it?

**Comment by Arcanemagus** [comment]
Also I notice from your package list that you have no service providers for this, you will want to install one of the linters listed here for the language(s) that you work in: http://atomlinter.github.io/

**Comment by steelbrain** [comment]
If I had to guess, you've cloned the linter repo. There are generally three ways to install linter, open a cmd or terminal and type this

#### Method 1

```
apm uninstall linter
apm install linter
```

#### Method 2

Open settings view -> install packages
Search for linter and click install

#### Method 3

```js
cd ~/.atom/packages
rm -rf linter
git clone --depth=1 https://github.com/atom-community/linter
cd linter
apm install
```
