### ISSUE TITLE
Failed to activate the linter package (EPERM: operation not permitted, write)

### ISSUE THREAD

**Issue by LendLord** [atom-community/linter#1025]
[Enter steps to reproduce below:]

1. Install linter
2. Error occured

**Atom Version**: 1.4.0-beta0
**System**: Unknown Windows Version (Windows 10)
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Failed to activate the linter package

```
At C:/Users/Lord/.atom/packages/linter/lib/linter-views.js: EPERM: operation not permitted, write

Error: C:/Users/Lord/.atom/packages/linter/lib/linter-views.js: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at Function.log (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\node.js:106:17)
    at enabled (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\debug.js:117:11)
    at Logger.debug (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\logger.js:92:31)
    at File.parse (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:573:14)
    at File.parseCode (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:691:20)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:167:12
    at File.wrap (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:639:16)
    at Pipeline.transform (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:165:17)
    at Object.exports.compile (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\babel.js:51:16)
    at compileFileAtPath (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:72:44)
    at Object.defineProperty.value [as .js] (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:203:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.<anonymous> (file:///C:/Users/Lord/.atom/packages/linter/lib/linter.coffee:3:15)
    at Object.<anonymous> (file:///C:/Users/Lord/.atom/packages/linter/lib/linter.coffee:1:1)
    at Module._compile (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.module.exports.activate (file:///C:/Users/Lord/.atom/packages/linter/lib/main.coffee:130:18)
    at Package.module.exports.Package.activateNow (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:183:20)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:92:15)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:524:21)
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:336:19
    at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\config.js:623:20
    at Emitter.module.exports.Emitter.emit (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\config.js:808:29)
    at Config.module.exports.Config.setRawValue (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\config.js:600:19)
    at Config.module.exports.Config.set (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\config.js:377:12)
    at Package.module.exports.Package.enable (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
  2x -3:28 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint",
      "achievements",
      "save-session",
      "docblockr",
      "whitespace",
      "atom-ternjs",
      "minimap-highlight-selected",
      "minimap-pigments",
      "minimap-selection",
      "minimap-split-diff",
      "linter-htmlhint",
      "linter-jshint",
      "linter-php"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "linter": {
    "alwaysTakeMinimumSpace": false,
    "ignoredMessageTypes": [
      "warning"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-php, v1.0.0
atom-alignment, v0.12.1
atom-beautify, vundefined
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
color-picker, v2.0.14
file-icons, v1.6.13
highlight-selected, v0.11.1
indent-guide-improved, v1.4.5
language-pascal, v0.14.0
linter, v1.11.3
minimap, v4.18.0
pigments, v0.19.3
sync-settings, v0.6.0
synced-sidebar, v0.4.3
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
tool-bar-main, v0.0.8
trailing-spaces, v0.3.2
tree-view-open-files, v0.3.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
If I had to guess, it's a bug in atom. Looks like babel is trying to write the transpiled file in the package root itself 
cc @maxbrunsfeld

**Comment by LendLord** [comment]
thanks for comment, but I tried with atom 1.3.1 and get the same error

**Comment by steelbrain** [comment]
Lets try an oldschool fix
```
apm uninstall linter
apm install linter
```

**Comment by LendLord** [comment]
nope, didn't help

**Comment by steelbrain** [comment]
Interesting, try this
```
mv ~/.atom ~/.atom-backup
apm install linter
```

**Comment by LendLord** [comment]
no, didn't help
may be it can help, I get the same error with default line-ending-selector package
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0-beta0
**System**: Unknown Windows Version
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0


### Stack Trace

Failed to load the line-ending-selector package

```
At C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EPERM: operation not permitted, write

Error: C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EPERM: operation not permitted, write
  at Error (native)
  at Object.fs.writeSync (fs.js:663:20)
  at SyncWriteStream.write (fs.js:1981:6)
  at Function.log (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\node.js:106:17)
  at enabled (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\node_modules\debug\debug.js:117:11)
  at Logger.debug (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\logger.js:92:31)
  at File.parse (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:573:14)
  at File.parseCode (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:691:20)
  at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:167:12
  at File.wrap (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:639:16)
  at Pipeline.transform (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:165:17)
  at Object.exports.compile (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\babel.js:51:16)
  at compileFileAtPath (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:72:44)
  at Object.defineProperty.value [as .js] (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:203:18)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:41:21)
  at Object.<anonymous> (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\node_modules\line-ending-selector\lib\main.js:16:22)
  at Module._compile (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:92:30)
  at Object.defineProperty.value [as .js] (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:204:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\native-compile-cache.js:41:21)
  at Package.module.exports.Package.requireMainModule (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:721:27)
  at C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:117:28
  at Package.module.exports.Package.measure (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:92:15)
  at Package.module.exports.Package.load (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:443:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\package-manager.js:393:14)
  at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\atom-environment.js:684:21)
  at module.exports (C:\Users\Lord\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\initialize-application-window.js:28:10)
  at setupWindow (file:///C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/static/index.js:85:5)
  at window.onload (file:///C:/Users/Lord/AppData/Local/atom/app-1.4.0-beta0/resources/app.asar/static/index.js:40:9)

```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
linter, v1.11.3

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
If you get the same error with a different package then it's definately an atom error

**Comment by LendLord** [comment]
yeah, its seems so, thanks you very much!
