### ISSUE TITLE
TypeError: helpers.findFile is not a function

### ISSUE THREAD

**Issue by sbromberger** [atom-community/linter#1036]
Not sure whether this is linter-related (I'd be grateful if you pointed me in the right direction if not), but I'm getting the following error message in Atom 1.3.1 when trying to save a file:

```
TypeError: helpers.findFile is not a function
    at Object.provider.lint (/Users/me/.atom/packages/linter-scalac/lib/linter-scalac.coffee:23:5)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/me/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/me/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/me/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/me/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/me/.atom/packages/linter/lib/editor-linter.js:30:20
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:588:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:633:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by steelbrain** [comment]
Sorry for the inconvenience @sbromberger 
I've just published a `linter-scalac` release that fixes it

**Comment by steelbrain** [comment]
If you still experience this issue then it's very likely an `apm` bug, I would recommend you do this
```bash
$ cd ~/.atom/packages/linter-scalac
$ npm install (or `apm install`, npm is recommended in this case)
```
