### ISSUE TITLE
linter error on startup

### ISSUE THREAD

**Issue by smunilla** [atom-community/linter#1038]
[Enter steps to reproduce below:]

1. On start

**Atom Version**: 0.192.0
**System**: linux 4.2.6-201.fc22.x86_64
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Failed to activate the linter package

```
At undefined is not a function

TypeError: undefined is not a function
    at EditorLinter.addGutter (/home/smunilla/.atom/packages/linter/lib/editor-linter.js:134:35)
    at EditorLinter.handleGutter (/home/smunilla/.atom/packages/linter/lib/editor-linter.js:127:16)
    at /home/smunilla/.atom/packages/linter/lib/editor-linter.js:57:13
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:540:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app/src/config.js:122:21)
    at new EditorLinter (/home/smunilla/.atom/packages/linter/lib/editor-linter.js:55:40)
    at EditorRegistry.create (/home/smunilla/.atom/packages/linter/lib/editor-registry.js:30:28)
    at Linter.createEditorLinter (/home/smunilla/.atom/packages/linter/lib/linter.coffee:159:35)
    at /home/smunilla/.atom/packages/linter/lib/linter.coffee:90:24
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:266:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ],
    "projectHome": "/home/smunilla/Development"
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
linter-pylint, v1.2.0
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
If I had to guess, Your atom is super-old, upgrade it
