### ISSUE TITLE
Linter crashes when linting javascript files

### ISSUE THREAD

**Issue by harig074** [atom-community/linter#1059]
I jave linter and linter-jshint packages installed. When I open a JS file, Linter package crashes with following error. This started happened since a recent update of linter/atom.

```
Uncaught TypeError: Invalid Point: (228, NaN)
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63
```

*Stacktrace
```
TypeError: Invalid Point: (228, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/harig/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom
```

**Comment by steelbrain** [comment]
Is this the bug you're experiencing? https://github.com/AtomLinter/linter-jshint/issues/197

**Comment by harig074** [comment]
I think it might just be. I tried disabling camel_case in my .jshintrc and linter seems to be stable now. Thanks for pointing this out.

**Comment by Arcanemagus** [comment]
Any reason you reopened this?

**Comment by harig074** [comment]
Had accidentally closed this issue. Since there was an issue referencing this one, I thought I'd reopen this.

**Comment by Arcanemagus** [comment]
As this isn't an issue with `linter` itself, I'm marking this as closed. Normally I'd suggest filing an issue on the linter provider that is throwing the error, but there already is one, so I'll just suggest subscribing to that one :wink:.
