### ISSUE TITLE
Uncaught TypeError: Invalid Point: (23, NaN)

### ISSUE THREAD

**Issue by nexsalesdev** [atom-community/linter#1061]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Linux Mint
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (23, NaN)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (23, NaN)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1339:59)
    at /home/joel/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/home/joel/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /home/joel/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/home/joel/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/home/joel/.atom/packages/linter/lib/linter-views.js:59:10)
    at /home/joel/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/home/joel/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/home/joel/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-projects"
    ],
    "themes": [
      "nucleus-dark-ui",
      "monokai"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-alignment, v0.12.1
autocomplete-modules, v1.3.1
change-case, v0.6.0
git-log, v0.4.1
linter, v1.11.3
linter-jshint, v1.2.2
minimap, v4.19.0
monokai, v0.18.0
nucleus-dark-ui, v0.7.4

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Looks like this is the same `esprima` bug we have been seeing everywhere else. If you are able you might try using `linter-eslint` with the `babel-eslint` parser or `linter-jscs` with the ESNext option (`babel-jscs` parser) as all linters using an `esprima` based parser are affected by this bug.
