### ISSUE TITLE
Uncaught TypeError: Invalid Point: (214, NaN)

### ISSUE THREAD

**Issue by alsoicode** [atom-community/linter#1068]
[Enter steps to reproduce below:]

1. Opened file for editing
2. Clicked in body of file

**Atom Version**: 1.4.3
**System**: Ubuntu 15.10
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (214, NaN)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (214, NaN)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1339:59)
    at /home/btaylor/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/home/btaylor/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /home/btaylor/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/home/btaylor/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/home/btaylor/.atom/packages/linter/lib/linter-views.js:59:10)
    at /home/btaylor/.atom/packages/linter/lib/linter.coffee:70:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/home/btaylor/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/home/btaylor/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -1:55 tree-view:remove (li.file.entry.list-item.status-added.selected)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pep8",
      "linter-pylint"
    ],
    "ignoredNames": [
      "*.pyc",
      "*.git",
      "*.idea",
      "*.vagrant"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter": {
    "errorPanelHeight": 76,
    "gutterPosition": "Left",
    "statusIconScope": "File"
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.2
atom-jade, v0.3.0
atom-ternjs, v0.13.2
auto-detect-indentation, v0.4.2
autoclose-html, v0.20.0
autocomplete-modules, v1.3.1
autocomplete-python, v1.6.1
django-templates, v0.5.0
file-icons, v1.6.14
highlight-selected, v0.11.2
language-dotenv, v1.0.0
linter, v1.11.3
linter-jshint, v1.3.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
project-manager, v2.7.6
seti-syntax, v0.4.1
seti-ui, v0.8.1
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
As `linter-jshint` seems to be your only provider you have installed I'm guessing that you are running into the [`camel_case` bug](https://github.com/jshint/jshint/pull/2846), or the [`esprima` parsing issue](https://github.com/jquery/esprima/issues/1457).

If you link to a file to test with we can verify which issue it is.

**Comment by alsoicode** [comment]
Interesting. Thank you for the links. I've attached the file in question.
[scrambler.js.zip](https://github.com/atom-community/linter/files/118004/scrambler.js.zip)

**Comment by Arcanemagus** [comment]
Hmmm, I don't see this issue in the file as it exists in that zip, do you?
![image](https://cloud.githubusercontent.com/assets/427137/12826145/75067bc8-cb2e-11e5-8f36-26556c09eb76.png)
![image](https://cloud.githubusercontent.com/assets/427137/12826164/8cf80fda-cb2e-11e5-90eb-2d1d7b5ce7c1.png)

**Comment by alsoicode** [comment]
No. This exception happened right after I opened the file and clicked on the active tab. It popped up in a red growl-style pop-up in the upper right hand corner of Atom and had a link to add the issue here.

**Comment by Arcanemagus** [comment]
So if you open the file as it exists in the zip file, you still see that error pop up?

**Comment by alsoicode** [comment]
Well, of course, now it doesn't do it :)  Maybe this was just a hiccup.

**Comment by Arcanemagus** [comment]
Oh I'm sure it was a valid issue, without the file in the state that triggered it though we can't do much more than know it happened :confused:.

Marking this as closed for now unless you can figure out the state that caused the issue, if you have the time.
