### ISSUE TITLE
Feature request: using absolute offset or delta as an alternative to [[row, col], [row, col]] for ranges…

### ISSUE THREAD

**Issue by hedefalk** [atom-community/linter#1075]
I'm using the linter-indie api to support IDE-like features for scala in ensime-atom https://github.com/ensime/ensime-atom

Currently the server backend gives me error message ranges in the form:

` {"beg":7429,"line":207,"col":57,"end":7435}``

Basically this means that I have an error starting at 207, 57 and the range is then 7435-7429 = 6 characters long. I just made the switch to try to use linter instead of our own homebrew error reporting where we could use the editor to calculate the positions. Using linter-indie however, it just doesn't feel feasable to open up each and everyone of the editor buffers to make the calculation even if they're maybe not even shown.

Currently my hacky code looks like this:

```
 # TODO: This is only true if error doesn't span two lines. Since we don't have buffer here it might be
    # good enough? Or not?
    range: [[note.line - 1, note.col - 1], [note.line - 1, note.col - 1 + (note.end - note.beg)]]
```
https://github.com/ensime/ensime-atom/blob/v0.34.0/lib/features/typechecking.coffee#L13

which sometimes gives the following error:

```
RangeError: Invalid string length
    at Object.stringify (native)
    at /Users/viktor/.atom/packages/linter/lib/validate.coffee:53:25
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (/Users/viktor/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (/Users/viktor/.atom/packages/linter/lib/message-registry.js:36:16)
    at /Users/viktor/.atom/packages/linter/lib/linter.coffee:35:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/viktor/.atom/packages/linter/lib/indie-registry.js:27:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Indie.setMessages (/Users/viktor/.atom/packages/linter/lib/indie.js:15:18)
    at Object.module.exports.indieLinter.addScalaNotes (/Users/viktor/dev/projects/atom-ensime/lib/features/typechecking.coffee:32:19)
    at module.exports.Ensime.statusbarOutput (/Users/viktor/dev/projects/atom-ensime/lib/ensime.coffee:208:20)
    at SwankParser.onMessage (/Users/viktor/dev/projects/atom-ensime/lib/client.coffee:34:9)
    at SwankParser.handleMessage (/Users/viktor/dev/projects/atom-ensime/lib/ensime-client/lisp/swank-protocol.js:77:8)
    at SwankParser.handleContent (/Users/viktor/dev/projects/atom-ensime/lib/ensime-client/lisp/swank-protocol.js:64:10)
    at SwankParser.execute (/Users/viktor/dev/projects/atom-ensime/lib/ensime-client/lisp/swank-protocol.js:55:20)
    at Socket.<anonymous> (/Users/viktor/dev/projects/atom-ensime/lib/client.coffee:51:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

```

Would it be possible to add the alternative range formats to support our use case?

**Comment by steelbrain** [comment]
We can not support alternative range formats, but we can help you transform those alternative range formats to the standard range format. You can use the [buffer position helper](https://atom.io/docs/api/v1.4.0/TextBuffer#instance-positionForCharacterIndex) to convert a character index into a position

**Comment by hedefalk** [comment]
Update: 

Sorry, I realize that the stack trace I got is from your usage of JSON.stringify. I guess I got to many errors and warnings?

**Comment by steelbrain** [comment]
@hedefalk That error happens everytime you give an empty text or html field, linter has been tested to work with upto 8k messages

**Comment by hedefalk** [comment]
@steelbrain That's exactly what I did before. Problem is I don't want to open up textbuffer for every warning in a huge project for files that aren't even shown.

But fair enough, I will try to modify the range format of the backend instead.

**Comment by hedefalk** [comment]
Ok! Cool, I'll look into if I have any empty messages than!

**Comment by steelbrain** [comment]
Also you already have the line number, if somehow you can not change the backend, you can do

 - Check if a buffer exists for that file path, if yes then use the correct range
 - Show a fake range where row is correct but start offset is set to zero and end offset set to Infinity
 - Everytime the user clicks the message to open that file, that file is opened and your text editor observer is called and you re-paint the messages of the newly opened file with correct coords

**Comment by hedefalk** [comment]
@steelbrain Thanks for the tips!

**Comment by hedefalk** [comment]
@steelbrain Sorry to spam you but you seem really helpful so I'll punish you with follow up questions:

All my lints have "msg" on them. However, something is very wrong. My atom instance dies at about 30 messages. I did a profiling and found the following:

<img width="1283" alt="screen shot 2016-02-09 at 15 59 23" src="https://cloud.githubusercontent.com/assets/116520/12920198/ef0f69f8-cf47-11e5-9a4a-9ff02b82cdc8.png">


Setting a breakpoint on my lints generation and doing JSON.stringify I noticed that for each push to the array the key-field is building up with weird super-escaped totalness:


This is for just 3 adds:


```
"[{"type":"Error","text":"not found: value asdf","range":{"start":{"row":23,"column":2},"end":{"row":23,"column":6}},"filePath":"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala","html":null,"trace":null,"class":"error","key":"{\"type\":\"Error\",\"text\":\"not found: value asdf\",\"range\":{\"start\":{\"row\":23,\"column\":2},\"end\":{\"row\":23,\"column\":6}},\"filePath\":\"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala\",\"html\":null,\"trace\":null,\"class\":\"error\"}"}]"




"[{"type":"Error","text":"not found: value asdf","range":{"start":{"row":23,"column":2},"end":{"row":23,"column":6}},"filePath":"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala","html":null,"trace":null,"class":"error","key":"{\"type\":\"Error\",\"text\":\"not found: value asdf\",\"range\":{\"start\":{\"row\":23,\"column\":2},\"end\":{\"row\":23,\"column\":6}},\"filePath\":\"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala\",\"html\":null,\"trace\":null,\"class\":\"error\",\"key\":\"{\\\"type\\\":\\\"Error\\\",\\\"text\\\":\\\"not found: value asdf\\\",\\\"range\\\":{\\\"start\\\":{\\\"row\\\":23,\\\"column\\\":2},\\\"end\\\":{\\\"row\\\":23,\\\"column\\\":6}},\\\"filePath\\\":\\\"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala\\\",\\\"html\\\":null,\\\"trace\\\":null,\\\"class\\\":\\\"error\\\"}\"}"},{"type":"Warning","text":"Unused import","range":{"start":{"row":3,"column":30},"end":{"row":3,"column":74}},"filePath":"/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/model/interpretations/InterpretationSorterTest.scala","html":null,"trace":null,"class":"warning","key":"{\"type\":\"Warning\",\"text\":\"Unused import\",\"range\":{\"start\":{\"row\":3,\"column\":30},\"end\":{\"row\":3,\"column\":74}},\"filePath\":\"/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/model/interpretations/InterpretationSorterTest.scala\",\"html\":null,\"trace\":null,\"class\":\"warning\"}"}]"



"[{"type":"Error","text":"not found: value asdf","range":{"start":{"row":23,"column":2},"end":{"row":23,"column":6}},"filePath":"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala","html":null,"trace":null,"class":"error","key":"{\"type\":\"Error\",\"text\":\"not found: value asdf\",\"range\":{\"start\":{\"row\":23,\"column\":2},\"end\":{\"row\":23,\"column\":6}},\"filePath\":\"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala\",\"html\":null,\"trace\":null,\"class\":\"error\",\"key\":\"{\\\"type\\\":\\\"Error\\\",\\\"text\\\":\\\"not found: value asdf\\\",\\\"range\\\":{\\\"start\\\":{\\\"row\\\":23,\\\"column\\\":2},\\\"end\\\":{\\\"row\\\":23,\\\"column\\\":6}},\\\"filePath\\\":\\\"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala\\\",\\\"html\\\":null,\\\"trace\\\":null,\\\"class\\\":\\\"error\\\",\\\"key\\\":\\\"{\\\\\\\"type\\\\\\\":\\\\\\\"Error\\\\\\\",\\\\\\\"text\\\\\\\":\\\\\\\"not found: value asdf\\\\\\\",\\\\\\\"range\\\\\\\":{\\\\\\\"start\\\\\\\":{\\\\\\\"row\\\\\\\":23,\\\\\\\"column\\\\\\\":2},\\\\\\\"end\\\\\\\":{\\\\\\\"row\\\\\\\":23,\\\\\\\"column\\\\\\\":6}},\\\\\\\"filePath\\\\\\\":\\\\\\\"/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/session/UserSession.scala\\\\\\\",\\\\\\\"html\\\\\\\":null,\\\\\\\"trace\\\\\\\":null,\\\\\\\"class\\\\\\\":\\\\\\\"error\\\\\\\"}\\\"}\"}"},{"type":"Warning","text":"Unused import","range":{"start":{"row":3,"column":30},"end":{"row":3,"column":74}},"filePath":"/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/model/interpretations/InterpretationSorterTest.scala","html":null,"trace":null,"class":"warning","key":"{\"type\":\"Warning\",\"text\":\"Unused import\",\"range\":{\"start\":{\"row\":3,\"column\":30},\"end\":{\"row\":3,\"column\":74}},\"filePath\":\"/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/model/interpretations/InterpretationSorterTest.scala\",\"html\":null,\"trace\":null,\"class\":\"warning\",\"key\":\"{\\\"type\\\":\\\"Warning\\\",\\\"text\\\":\\\"Unused import\\\",\\\"range\\\":{\\\"start\\\":{\\\"row\\\":3,\\\"column\\\":30},\\\"end\\\":{\\\"row\\\":3,\\\"column\\\":74}},\\\"filePath\\\":\\\"/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/model/interpretations/InterpretationSorterTest.scala\\\",\\\"html\\\":null,\\\"trace\\\":null,\\\"class\\\":\\\"warning\\\"}\"}"},{"type":"Warning","text":"Unused import","range":{"start":{"row":7,"column":34},"end":{"row":7,"column":89}},"filePath":"/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/model/interpretations/InterpretationSorterTest.scala","html":null,"trace":null,"class":"warning","key":"{\"type\":\"Warning\",\"text\":\"Unused import\",\"range\":{\"start\":{\"row\":7,\"column\":34},\"end\":{\"row\":7,\"column\":89}},\"filePath\":\"/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/model/interpretations/InterpretationSorterTest.scala\",\"html\":null,\"trace\":null,\"class\":\"warning\"}"}]"

```


Current guess is that indie api doesn't support multiple calls to setMessages without a `deleteMessages()`call inbetween, gonna try that now…

**Comment by steelbrain** [comment]
Please note that the messages set by Indie API have a `scope` set to `Project`. So if you set messages twice, the previous messages will be replaced by the new ones.

Another thing to note is that, you **must** provide different objects to linter each time you set messages, if you send in the same objects you'll be screwing up a lot of optimizations and weird things like ^ that one will appear.

By different I mean `{} !== {}`, but `a = {}; a === a`. Therefore you should not store your messages somewhere and keep setting them again and again, you should construct completely new objects. But, if your backend doesn't support giving you a new message object each time you want to do that, you can always `JSON.stringify` then `JSON.parse` the messages before sending them to linter, this will create new objects of the same structure

**Comment by hedefalk** [comment]
Ah, ok. Yeah, backend sends me messages incrementally so I need to store them and add on each bunch received. So a `setMessages(JSON.parse(JSON.stringify(messages)))` will make it a ok?

**Comment by steelbrain** [comment]
That should work

**Comment by hedefalk** [comment]
@steelbrain Thanks, that seems to work!
