### ISSUE TITLE
Error: Invalid TextEditor provided Ubuntu x64

### ISSUE THREAD

**Issue by ArekSredzki** [atom-community/linter#1077]
Today I started receiving the following error whenever I open a new file or save it.

```
Error: Invalid TextEditor provided
    at _validateEditor (/home/asredzki/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:143:11)
    at Object.rangeFromLineNumber (/home/asredzki/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.js:164:3)
    at /home/asredzki/.atom/packages/linter-jshint/lib/main.coffee:88:31
    at Array.map (native)
    at /home/asredzki/.atom/packages/linter-jshint/lib/main.coffee:77:25
    at process._tickCallback (node.js:368:9)
```

**Comment by ArekSredzki** [comment]
Created the ticket over linter/linter-jshint#205

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/atom-linter/pull/106
For future visitors, workaround it by upgrading your Atom to 1.4.0+
