### ISSUE TITLE
Error: sh: mysql: line 1: syntax error

### ISSUE THREAD

**Issue by akmur** [atom-community/linter#1092]
Hello, I get the weirdest error when I try to lint an scss file:

`Error: sh: mysql: line 1: syntax error: unexpected end of file sh: error importing function definition for mysql' sh: mysqladmin: line 1: syntax error: unexpected end of file sh: error importing function definition formysqladmin'

Error: sh: mysql: line 1: syntax error: unexpected end of file
sh: error importing function definition for `mysql'
sh: mysqladmin: line 1: syntax error: unexpected end of file
sh: error importing function definition for `mysqladmin'
    at parameters.exit (/Users/alessandromuraro/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.js:47:27)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)`

I already tried to resintall the packages and to stop MAMP but the issue stays the same... any clue?

Thanks!

**Comment by steelbrain** [comment]
This is actually a possible bug in `linter-scss-lint `, please reopen this issue there
