### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by k2b6s9j** [atom-community/linter#705]
Encountered while using `master@a292cd757489d6a3ddc70a7e03c5d127e285b587`.
```
TypeError: Cannot read property 'start' of undefined
  at Function.module.exports.Range.fromObject (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:35:31)
  at TextBuffer.module.exports.TextBuffer.clipRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:943:21)
  at TextBuffer.module.exports.TextBuffer.markRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:674:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1383:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1269:59)
  at /Users/kepler/Developer/AtomLinter/Linter/lib/linter-views.coffee:102:43
  at Array.forEach (native)
  at LinterViews.renderPanelMarkers (/Users/kepler/Developer/AtomLinter/Linter/lib/linter-views.coffee:100:15)
  at LinterViews.render (/Users/kepler/Developer/AtomLinter/Linter/lib/linter-views.coffee:47:6)
  at /Users/kepler/Developer/AtomLinter/Linter/lib/linter-views.coffee:37:8
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.set (/Users/kepler/Developer/AtomLinter/Linter/lib/messages.coffee:47:14)
  at Linter.setMessages (/Users/kepler/Developer/AtomLinter/Linter/lib/linter-plus.coffee:66:15)
  at /Users/kepler/Developer/AtomLinter/Linter/lib/editor-linter.coffee:71:19
```

**Comment by k2b6s9j** [comment]
Only occurs with [`linter-flint`](https://github.com/AtomLinter/linter-flint) installed and enabled.

**Comment by steelbrain** [comment]
It's because `linter-flint` is providing an invalid range object, that range object is undefined.

**Comment by steelbrain** [comment]
You might wanna open it in that repo :smiley:

**Comment by k2b6s9j** [comment]
Why should `linter-flint` have to provide a Range if it is just trying to provide some messages to the Project tab? Flint doesn't even associate errors with specific files. It shows you errors with your project itself.

**Comment by steelbrain** [comment]
Right!

**Comment by steelbrain** [comment]
Can you create a minimal repro example?

**Comment by steelbrain** [comment]
Closing as a lot of stuff has changed since this was opened and I haven't had a repro yet
