### ISSUE TITLE
`undefined` argument in `processMultiLine`

### ISSUE THREAD

**Issue by kaeluka** [atom-community/linter#729]
0. Insert `assert(@text)` in processMultiline function in `views/message.coffee`
1. Use linter with linter-hdevtools
2. Open a haskell buffer with linter issues

If the `assert` is not there, atom will crash when it attempts to call `text.split`. However, the editor thinks this bug report has already been sent. The one that's been sent is about a completely different location though.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.2.3

### Stack Trace

Uncaught AssertionError: undefined == true

```
At assert.js:87

AssertionError: undefined == true
  at Function.Message.processMultiLine (/Users/stebr742/.atom/packages/linter/lib/views/message.coffee:53:5)
  at Function.Message.renderMessage (/Users/stebr742/.atom/packages/linter/lib/views/message.coffee:46:30)
  at linter-message.Message.attachedCallback (/Users/stebr742/.atom/packages/linter/lib/views/message.coffee:9:26)
  at linter-panel.<anonymous> (/Users/stebr742/.atom/packages/linter/lib/views/bottom-panel.js:41:12)
  at Array.forEach (native)
  at linter-panel.updateMessages (/Users/stebr742/.atom/packages/linter/lib/views/bottom-panel.js:40:14)
  at LinterViews.renderPanelMessages (/Users/stebr742/.atom/packages/linter/lib/linter-views.coffee:95:12)
  at LinterViews.render (/Users/stebr742/.atom/packages/linter/lib/linter-views.coffee:46:6)
  at /Users/stebr742/.atom/packages/linter/lib/linter-views.coffee:37:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/stebr742/.atom/packages/linter/lib/messages.coffee:24:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/stebr742/.atom/packages/linter/lib/editor-linter.coffee:76:22
  at process._tickCallback (node.js:367:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-hlint",
      "linter-chktex",
      "ide-haskell"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.3
language-haskell, v1.1.8
language-latex, v0.6.1
latexer, v0.2.3
linter, v1.2.3
linter-hdevtools, v0.8.0
minimap, v4.11.2
minimap-find-and-replace, v4.2.0
red-wavy-underline, v0.3.0
skim-displayline, v0.0.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
@kaeluka, FYI, you could copy Atom error report to clipboard, even if it says that bug was reported, and paste it here.

Anyway, if linter-hdevtools sets `multline`, and doesn't supply `text`, that is a mistake in linter-hdevtools. More than that, it doesn't seem to supply `html` as well, so that's definitely a problem. Linter should probably handle this case more gracefully, though.

@steelbrain, does Linter API require at least one of `html` or `text` set? If not, then could add check `and/if message.text?` at lines 42, 44 of `views/message.coffee`. If it does, then should check that in `validateMessages`. Check could look like `throw ... unless result.text? or result.html?`. Having both `html` and `text` could be treated as error as well, depending.

**Comment by lierdakil** [comment]
Wait a second. linter-hdevtools uses legacy API. How does `message.multiline` get set then?

**Comment by steelbrain** [comment]
@lierdakil We have a check like that pending in a PR

**Comment by steelbrain** [comment]
No feedback provided for more than a week, closing.
