### ISSUE TITLE
spawn EACCES Error at all the Times

### ISSUE THREAD

**Issue by Dygerati** [atom-community/linter#740]
So, when I startup Atom, open a file, save a file, or do much of anything, I get the much feared red popup that reads as follows:

**spawn EACCCES**
```Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at /Users/jthie1/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.coffee:15:38
  at Object.module.exports.Helpers.exec (/Users/jthie1/.atom/packages/linter-jshint/node_modules/atom-linter/lib/helpers.coffee:14:16)
  at Object.provider.lint (/Users/jthie1/.atom/packages/linter-jshint/lib/main.coffee:24:24)
  at /Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:69:26
  at currentLinter (/Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:68:20)
  at /Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:64:26)
  at /Users/jthie1/.atom/packages/linter/lib/editor-linter.coffee:57:27```


Any thoughts?

EDIT - Forgot to mention, here are relevant versions:
Atom: 1.0.2
Linter: 1.2.3
Linter-jshint: 1.0.5

**Comment by steelbrain** [comment]
EACCESS is a Node JS internal error, it means you don't have access to the bin file or it's not executable, nothing to do with linter or linter-jshint

**Comment by steelbrain** [comment]
Can you please provide a minimal repro example?

**Comment by steelbrain** [comment]
This has been fixed in jshint by the recent release.
