### ISSUE TITLE
Missing type field on Linter Response, Got: type,text,filePath,range

### ISSUE THREAD

**Issue by ChristianGrech** [atom-community/linter#756]
Getting the below error quite often.

Error: Missing type field on Linter Response, Got: type,text,filePath,range
  at Object.module.exports.validateMessages (C:\Users\Christian\.atom\packages\linter\lib\helpers.coffee:20:19)
  at C:\Users\Christian\.atom\packages\linter\lib\messages.coffee:18:17
  at Emitter.module.exports.Emitter.emit (C:\Users\Christian\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Christian\.atom\packages\linter\lib\editor-linter.coffee:76:22
  at process._tickCallback (node.js:367:9)

**Comment by steelbrain** [comment]
That's actually a problem with the provider, nothing's wrong with the base :)

**Comment by Arcanemagus** [comment]
Just for reference for anyone coming to this later, this was fixed in https://github.com/AtomLinter/linter-php/issues/51.
