### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('w...

### ISSUE THREAD

**Issue by Kerosene2000** [atom-community/linter#795]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.0

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('warning:-'glulookat' is deprecated') contains HTML space characters, which are not valid in tokens.

```
At /Users/crenault/Dropbox/.atom/packages/linter/lib/views/message.coffee:30

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('warning:-'glulookat' is deprecated') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at Function.Message.renderRibbon (/Users/crenault/Dropbox/.atom/packages/linter/lib/views/message.coffee:30:18)
  at linter-message.Message.attachedCallback (/Users/crenault/Dropbox/.atom/packages/linter/lib/views/message.coffee:5:26)
  at linter-panel.<anonymous> (/Users/crenault/Dropbox/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
  at Array.forEach (native)
  at linter-panel.updateMessages (/Users/crenault/Dropbox/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
  at LinterViews.renderPanelMessages (/Users/crenault/Dropbox/.atom/packages/linter/lib/linter-views.coffee:107:12)
  at LinterViews.renderLineMessages (/Users/crenault/Dropbox/.atom/packages/linter/lib/linter-views.coffee:51:8)
  at /Users/crenault/Dropbox/.atom/packages/linter/lib/linter-plus.coffee:101:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/crenault/Dropbox/.atom/packages/linter/lib/editor-linter.coffee:14:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1591:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:346:12)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:175:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:185:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:121:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:728:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:119:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1370:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1582:9)
  at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1369:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:552:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -1:49.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:40.4.0 core:select-to-bottom (atom-text-editor.editor.is-focused)
     -1:39.8.0 core:copy (atom-text-editor.editor.is-focused)
     -1:31 core:page-down (atom-text-editor.editor.is-focused)
  8x -1:30 core:move-up (atom-text-editor.editor.is-focused)
     -1:29.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:27.3.0 core:select-to-bottom (atom-text-editor.editor.is-focused)
     -1:26.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:26 core:save (atom-text-editor.editor.is-focused)
     -1:08.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -1:08.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "~/Dropbox/42jobs",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.o"
    ],
    "disabledPackages": [
      "autocomplete-atom-api",
      "snippets",
      "autocomplete-clang"
    ],
    "destroyEmptyPanes": false
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
header-42, v0.1.1
highlight-selected, v0.10.1
linter, v1.3.0
linter-clang, v3.0.0
linter-coffeelint, v1.0.1
minimap, v4.12.1
selection-counter, v0.1.1
tab-control, v0.6.7

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
It's actually a problem with the linter, he's providing an invalid `type` on messages. but I agree that we should still be taking care of it

**Comment by k2b6s9j** [comment]
@steelbrain Is the issue from coffeelint or clang?

**Comment by steelbrain** [comment]
@k2b6s9j clang I suppose. `'warning:-'glulookat` is an invalid type.

**Comment by k2b6s9j** [comment]
Huh. I wonder why clang would be suppling that. My regex should only be passing warning...

**Comment by k2b6s9j** [comment]
@Kerosene2000 would you mind sharing the file you were editing when the error occurred?

**Comment by Kerosene2000** [comment]
yup ! here it is [split view glfw example file](https://github.com/glfw/glfw/blob/master/examples/splitview.c).

**Comment by Kerosene2000** [comment]
Somebody is on the fix of this error ?

**Comment by steelbrain** [comment]
@Kerosene2000 We are still investigating this bug :)

**Comment by k2b6s9j** [comment]
I just fixed the Java variant of this bug. I will fix the Clang and GCC variants now.

**Comment by k2b6s9j** [comment]
This is an issue of regex capturing more than it should for the type. An issue totally on my end as a developer.

**Comment by k2b6s9j** [comment]
This particular bug in `linter-clang` should be fixed now. @Kerosene2000 mind testing?

**Comment by Kerosene2000** [comment]
Yup good with my file ! thank you ! and have a good day :smile:

**Comment by steelbrain** [comment]
Closing as fixed in `linter-clang`.

**Comment by cavejay** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.4


### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('warning:-'daemon' is deprecated') contains HTML space characters, which are not valid in tokens.

```
At /Users/Michael/.atom/packages/linter/lib/views/message.coffee:28

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('warning:-'daemon' is deprecated') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at Function.Message.renderRibbon (/Users/Michael/.atom/packages/linter/lib/views/message.coffee:28:18)
  at linter-message.Message.attachedCallback (/Users/Michael/.atom/packages/linter/lib/views/message.coffee:5:26)
  at linter-panel.<anonymous> (/Users/Michael/.atom/packages/linter/lib/views/bottom-panel.js:41:12)
  at Array.forEach (native)
  at linter-panel.updateMessages (/Users/Michael/.atom/packages/linter/lib/views/bottom-panel.js:40:14)
  at LinterViews.renderPanelMessages (/Users/Michael/.atom/packages/linter/lib/linter-views.coffee:93:12)
  at /Users/Michael/.atom/packages/linter/lib/linter-views.coffee:39:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at linter-bottom-tab.<anonymous> (/Users/Michael/.atom/packages/linter/lib/views/bottom-container.coffee:23:17)

```

### Commands

```
     -8:41.3.0 core:move-left (atom-text-editor.editor.is-focused)
 12x -8:34.1.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -8:31.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:22.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -8:21.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -8:21.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -8:21.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -7:52.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:51.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -7:51 core:copy (atom-text-editor.editor.is-focused)
     -7:44.2.0 core:paste (atom-text-editor.editor.is-focused)
     -3:51.9.0 settings-view:open (a.btn-issue.btn.btn-error)
  6x -2:24.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:22.6.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -2:18.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:01.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
gnippets, v0.1.0
linter, v1.3.4
linter-clang, v3.1.3
minimap, v4.12.2
monokai, v0.17.0
overscroll, v0.1.0
react, v0.12.6
remote-edit, v1.8.15
space-tab, v0.4.2

# Dev
No dev packages
```
