### ISSUE TITLE
Error: Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by yriveiro** [atom-community/linter#805]
Atom: 1.0.4
Linter: 1.3.0

Coding php (I have installed linter-php package also, version 1.0.2) I have this error:
```
Error: Missing html/text field on Linter Response
  at /Users/yriveiro/.atom/packages/linter/lib/validate.coffee:24:19
  at Array.forEach (native)
  at Object.module.exports.Validate.messages (/Users/yriveiro/.atom/packages/linter/lib/validate.coffee:20:14)
  at MessageRegistry.set (/Users/yriveiro/.atom/packages/linter/lib/message-registry.coffee:22:18)
  at /Users/yriveiro/.atom/packages/linter/lib/linter-plus.coffee:27:17
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/yriveiro/.atom/packages/linter/lib/linter-registry.coffee:57:32
  at process._tickCallback (node.js:367:9)
```

**Comment by steelbrain** [comment]
This is an issue with a linter provider and should be opened there instead of the core repo. If You were editing a php file when this issue occured, I've pushed a patch release that fixes it.
