### ISSUE TITLE
Error: Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by masiqbal** [atom-community/linter#806]
Error: Missing html/text field on Linter Response
  at /Users/iqbal/.atom/packages/linter/lib/validate.coffee:24:19
  at Array.forEach (native)
  at Object.module.exports.Validate.messages (/Users/iqbal/.atom/packages/linter/lib/validate.coffee:20:14)
  at MessageRegistry.set (/Users/iqbal/.atom/packages/linter/lib/message-registry.coffee:22:18)
  at /Users/iqbal/.atom/packages/linter/lib/linter-plus.coffee:27:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/iqbal/.atom/packages/linter/lib/linter-registry.coffee:57:32
  at process._tickCallback (node.js:367:9)

**Comment by Eschon** [comment]
Similar to #805 and #799 this is probably an error in the linter provider. So you should probably open an issue there.

**Comment by steelbrain** [comment]
Closing based on comment above
