### ISSUE TITLE
[ERB] Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList'

### ISSUE THREAD

**Issue by AlexWayfer** [atom-community/linter#832]
[Enter steps to reproduce below:]

1. Open .erb-file
2. Ctrl+S

**Atom Version**: 1.0.7
**System**: linux 4.1.4-1-ARCH
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.4

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('unknown-regexp options - ttar') contains HTML space characters, which are not valid in tokens.

```
At /home/alex/.atom/packages/linter/lib/views/message.coffee:0

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('unknown-regexp options - ttar') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at Function.Message.renderRibbon (/home/alex/.atom/packages/linter/lib/views/message.coffee:57:20)
    at linter-message.Message.attachedCallback (/home/alex/.atom/packages/linter/lib/views/message.coffee:19:32)
    at linter-panel.<anonymous> (/home/alex/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
    at Array.forEach (native)
    at linter-panel.updateMessages (/home/alex/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
    at LinterViews.renderPanelMessages (/home/alex/.atom/packages/linter/lib/linter-views.coffee:190:25)
    at LinterViews.renderLineMessages (/home/alex/.atom/packages/linter/lib/linter-views.coffee:91:21)
    at /home/alex/.atom/packages/linter/lib/linter-plus.coffee:154:30
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /home/alex/.atom/packages/linter/lib/editor-linter.coffee:29:27
```

### Commands

```
     -3:25.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:24.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:20.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:12.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:11.9.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -3:09.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:07.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:49.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:45.2.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:43.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:38.6.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:38.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:34.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:32.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:29.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:28.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "tree-view-open-files"
    ]
  },
  "linter": {
    "showErrorTabLine": true,
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.3.0
auto-detect-indentation, v0.4.2
autoclose-html, v0.18.0
autocomplete-html-entities, v0.1.0
autocomplete-ruby, v0.1.0
indentation-indicator, v0.6.0
linter, v1.3.4
linter-reek, v2.0.0
linter-rubocop, v0.3.1
linter-ruby, v1.0.1
monokai, v0.17.0
ruby-block, v0.3.5
ruby-define-method, v0.2.1

# Dev
No dev packages
```

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: linux 4.1.4-1-ARCH
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.4

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('unknown-regexp options - bt') contains HTML space characters, which are not valid in tokens.

```
At /home/alex/.atom/packages/linter/lib/views/message.coffee:0

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('unknown-regexp options - bt') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at Function.Message.renderRibbon (/home/alex/.atom/packages/linter/lib/views/message.coffee:57:20)
    at linter-message.Message.attachedCallback (/home/alex/.atom/packages/linter/lib/views/message.coffee:19:32)
    at linter-panel.<anonymous> (/home/alex/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
    at Array.forEach (native)
    at linter-panel.updateMessages (/home/alex/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
    at LinterViews.renderPanelMessages (/home/alex/.atom/packages/linter/lib/linter-views.coffee:190:25)
    at LinterViews.renderLineMessages (/home/alex/.atom/packages/linter/lib/linter-views.coffee:91:21)
    at /home/alex/.atom/packages/linter/lib/linter-plus.coffee:154:30
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /home/alex/.atom/packages/linter/lib/editor-linter.coffee:29:27
```

### Commands

```
     -3:25.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:24.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:20.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:12.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:11.9.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -3:09.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:07.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:49.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:45.2.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:43.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:38.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:38.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:34.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:32.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:29.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:28.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "tree-view-open-files"
    ]
  },
  "linter": {
    "showErrorTabLine": true,
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.3.0
auto-detect-indentation, v0.4.2
autoclose-html, v0.18.0
autocomplete-html-entities, v0.1.0
autocomplete-ruby, v0.1.0
indentation-indicator, v0.6.0
linter, v1.3.4
linter-reek, v2.0.0
linter-rubocop, v0.3.1
linter-ruby, v1.0.1
monokai, v0.17.0
ruby-block, v0.3.5
ruby-define-method, v0.2.1

# Dev
No dev packages
```

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: linux 4.1.4-1-ARCH
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.4

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('unterminated-regexp meets end of fil') contains HTML space characters, which are not valid in tokens.

```
At /home/alex/.atom/packages/linter/lib/views/message.coffee:0

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('unterminated-regexp meets end of fil') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at Function.Message.renderRibbon (/home/alex/.atom/packages/linter/lib/views/message.coffee:57:20)
    at linter-message.Message.attachedCallback (/home/alex/.atom/packages/linter/lib/views/message.coffee:19:32)
    at linter-panel.<anonymous> (/home/alex/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
    at Array.forEach (native)
    at linter-panel.updateMessages (/home/alex/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
    at LinterViews.renderPanelMessages (/home/alex/.atom/packages/linter/lib/linter-views.coffee:190:25)
    at LinterViews.renderLineMessages (/home/alex/.atom/packages/linter/lib/linter-views.coffee:91:21)
    at /home/alex/.atom/packages/linter/lib/linter-plus.coffee:154:30
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /home/alex/.atom/packages/linter/lib/editor-linter.coffee:29:27
```

### Commands

```
     -3:25.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:24.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:20.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:12.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:12 editor:newline (atom-text-editor.editor.is-focused)
  5x -3:09.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:07.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:49.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:45.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:43.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:38.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:38.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:34.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:32.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:29.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:28.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "tree-view-open-files"
    ]
  },
  "linter": {
    "showErrorTabLine": true,
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.3.0
auto-detect-indentation, v0.4.2
autoclose-html, v0.18.0
autocomplete-html-entities, v0.1.0
autocomplete-ruby, v0.1.0
indentation-indicator, v0.6.0
linter, v1.3.4
linter-reek, v2.0.0
linter-rubocop, v0.3.1
linter-ruby, v1.0.1
monokai, v0.17.0
ruby-block, v0.3.5
ruby-define-method, v0.2.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
A linter provider bug, not a linter bug. You should post it in the provider repo.

**Comment by Arcanemagus** [comment]
To help narrow it down, from a quick Google search it looks like that _might_ be `linter-ruby`, but it could be any of the 3 Ruby linters you have installed. Try disabling them all, then re-enabling them one by one to figure out which one isn't passing a message back to `linter` properly.

**Comment by AlexWayfer** [comment]
Okay, thank you.

**Comment by Arcanemagus** [comment]
Thanks for reporting the issue, hopefully we can get it narrowed down to the correct package and fixed :wink:.
