### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by gustaflindqvist** [atom-community/linter#850]
**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'setAttribute' of undefined

```
At /Users/gustaf/.atom/packages/linter/lib/ui/message-element.js:38

TypeError: Cannot read property 'setAttribute' of undefined
  at linter-message.updateVisibility (/Users/gustaf/.atom/packages/linter/lib/ui/message-element.js:38:217)
  at BottomPanel.setMessages (/Users/gustaf/.atom/packages/linter/lib/ui/bottom-panel.js:56:24)
  at LinterViews.render (/Users/gustaf/.atom/packages/linter/lib/linter-views.coffee:41:12)
  at /Users/gustaf/.atom/packages/linter/lib/linter.coffee:30:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.updatePublic (/Users/gustaf/.atom/packages/linter/lib/message-registry.js:108:20)
  at UpdateMessages (/Users/gustaf/.atom/packages/linter/lib/message-registry.js:35:17)

```

### Commands

```
     -0:03.9.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "spacegray-dark-ui",
      "base16-ocean-dark-spacegray"
    ],
    "disabledPackages": [
      "autocomplete-elixir"
    ]
  },
  "linter": {
    "ignoredLinterErrors": []
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
base16-ocean-dark-spacegray, v0.10.0
emmet, v2.3.12
language-elixir, v0.5.2
linter, v1.4.3
linter-elixirc, v0.2.2
linter-reek, v2.0.0
linter-rubocop, v0.3.1
linter-ruby, v1.0.1
minimap, v4.12.3
react, v0.12.6
ruby-define-method, v0.2.1
spacegray-dark-ui, v0.12.0
vim-mode, v0.58.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Any way to repro it? Did it happen just once or does it still happen?

**Comment by Arcanemagus** [comment]
If this is anything like the other issues with that stack trace this is caused by one of the linter providers sending an invalid message. @gustaflindqvist can you try disabling your `linter-*` plugins and re-enabling them one by one till this crops back up again (linting the files you were when this first showed up).

**Comment by gustaflindqvist** [comment]
@Arcanemagus Found a way to repro it again in Atom. Going to try to disable my ```linter-*``` one by one.

**Comment by Arcanemagus** [comment]
Do you have steps to reproduce it? The errors in that bug have been fixed, so it would be a different stack trace if you are getting that message.

**Comment by thibaudgg** [comment]
I got this one along #456 as well.

**Comment by Arcanemagus** [comment]
The linter plugin has been entirely re-written since #456 was filed, so you may have the same title but an entirely different stack trace (which would be the important part here).

Do either of you two have steps to reproduce this so it can be diagnosed and worked on @gustaflindqvist and @thibaudgg?

**Comment by thibaudgg** [comment]
It happens when I edit or save a Ruby file (using: linter-reek, linter-ruby, linter-rubocop).
After that I got an empty "warning" error:
 
![screen shot 2015-08-25 at 08 58 00](https://cloud.githubusercontent.com/assets/1322/9460538/69e60328-4b07-11e5-83c2-435b9a00cbe0.png)

Backtraces:

```
/Users/Thibaud/.atom/packages/linter/lib/ui/message-element.js:87

TypeError: undefined is not a function
    at Function.getMessage (/Users/Thibaud/.atom/packages/linter/lib/ui/message-element.js:87:115)
    at linter-message.attachedCallback (/Users/Thibaud/.atom/packages/linter/lib/ui/message-element.js:46:32)
    at BottomPanel.setMessages (/Users/Thibaud/.atom/packages/linter/lib/ui/bottom-panel.js:55:22)
    at LinterViews.render (/Users/Thibaud/.atom/packages/linter/lib/linter-views.coffee:70:18)
    at /Users/Thibaud/.atom/packages/linter/lib/linter.coffee:40:30
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at MessageRegistry.updatePublic (/Users/Thibaud/.atom/packages/linter/lib/message-registry.js:108:20)
    at UpdateMessages (/Users/Thibaud/.atom/packages/linter/lib/message-registry.js:35:17)
```

```
/Users/Thibaud/.atom/packages/linter/lib/ui/message-element.js:38

TypeError: Cannot read property 'setAttribute' of undefined
    at linter-message.updateVisibility (/Users/Thibaud/.atom/packages/linter/lib/ui/message-element.js:38:217)
    at BottomPanel.setMessages (/Users/Thibaud/.atom/packages/linter/lib/ui/bottom-panel.js:56:24)
    at LinterViews.render (/Users/Thibaud/.atom/packages/linter/lib/linter-views.coffee:70:18)
    at /Users/Thibaud/.atom/packages/linter/lib/linter.coffee:40:30
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at MessageRegistry.updatePublic (/Users/Thibaud/.atom/packages/linter/lib/message-registry.js:108:20)
    at UpdateMessages (/Users/Thibaud/.atom/packages/linter/lib/message-registry.js:35:17)
```

**Comment by gustaflindqvist** [comment]
I'm getting  the exact same stack trace error as @thibaudgg
<https://github.com/thibaudgg>

2015-08-25 8:59 GMT+02:00 Thibaud Guillaume-Gentil <notifications@github.com

**Comment by Arcanemagus** [comment]
@thibaudgg @gustaflindqvist 

I went through the debugging steps I outlined earlier and here is the critical information both of you were missing:

* `linter-reek` is the only one causing an error, disabling that causes the issues to stop showing up.
* The Ruby file must have some content, an empty Ruby file doesn't cause any issues.

I've filed an issue over there to hopefully get this sorted out. For now I would recommend disabling `linter-reek` till the author of that plugin fixes this.

**Comment by thibaudgg** [comment]
You're right, disabling `linter-reek` solve this issue for me.
Thanks for having opened https://github.com/AtomLinter/linter-reek/issues/11.

**Comment by steelbrain** [comment]
I think this can be safely closed now. as we're validating the messages strictly in the latest version.

**Comment by gustaflindqvist** [comment]
Yes! +1
