### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeAttribute' of undefined

### ISSUE THREAD

**Issue by bogdanRada** [atom-community/linter#855]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 15.04
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'removeAttribute' of undefined

```
At /home/raul/.atom/packages/linter/lib/ui/message-element.js:38

TypeError: Cannot read property 'removeAttribute' of undefined
    at linter-message.updateVisibility (/home/raul/.atom/packages/linter/lib/ui/message-element.js:38:134)
    at BottomPanel.setMessages (/home/raul/.atom/packages/linter/lib/ui/bottom-panel.js:56:24)
    at LinterViews.render (/home/raul/.atom/packages/linter/lib/linter-views.coffee:70:18)
    at /home/raul/.atom/packages/linter/lib/linter.coffee:40:30
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at MessageRegistry.updatePublic (/home/raul/.atom/packages/linter/lib/message-registry.js:108:20)
    at UpdateMessages (/home/raul/.atom/packages/linter/lib/message-registry.js:35:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter": {
    "showErrorTabLine": true,
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.4
badges, v1.1.2
clip-history, v0.1.11
coffee-navigator, v0.0.16
color-picker, v2.0.11
git-diff-details, v0.20.0
git-go, v1.0.1
git-hide, v0.1.0
git-log, v0.4.1
git-wip, v0.1.3
jshint, v1.3.10
jsonlint, v1.1.2
language-diff, v0.3.1
language-less, v0.28.2
language-yaml, v0.24.0
line-diff-details, v1.1.2
linter, v1.4.3
linter-9e-sass, v0.5.0
linter-bootlint, v0.0.6
linter-chktex, v1.0.0
linter-coffeelint, v1.0.2
linter-csslint, v1.0.5
linter-erb, v0.1.1
linter-flint, v0.1.1
linter-flow, v0.1.6
linter-haml, v1.0.0
linter-handlebars, v2.1.0
linter-htmlhint, v0.1.1
linter-js-yaml, v1.1.1
linter-jscs, v2.0.4
linter-less, v2.1.0
linter-lsc, v2.0.1
linter-markdown, v0.1.0
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-phpmd, v1.0.0
linter-reek, v2.0.0
linter-rubocop, v0.3.2
linter-ruby, v1.0.2
linter-scss-lint, v2.0.0
linter-shellcheck, v1.0.1
linter-slim, v1.0.0
linter-stylelint, v0.4.0
linter-stylint, v2.0.0
linter-swiftc, v2.0.0
linter-tidy, v1.0.1
linter-tslint, v0.3.0
linter-xmllint, v0.0.7
local-history, v3.2.3
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
open-recent, v2.3.0
project-manager, v1.15.11
recent-projects, v0.8.3
run-in-terminal, v0.4.2
sublime-word-navigation, v0.1.2
travis-ci-status, v0.16.0
tree-view-git-branch, v0.0.2
tree-view-git-modified, v0.5.10
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.1.2
tualo-git-context, v0.6.14

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Do you have any steps to reproduce this?

**Comment by bogdanRada** [comment]
i think i found the culprit : i had this package installed linter-rubocop-caseywebdev which was probably interfering with some other package. i think it can be closed.
