### ISSUE TITLE
Uncaught TypeError: Invalid Point: (2, NaN)

### ISSUE THREAD

**Issue by mrtnbroder** [atom-community/linter#864]
[Enter steps to reproduce below:]

1. Open a .js file

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.4.3

### Stack Trace

Uncaught TypeError: Invalid Point: (2, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (2, NaN)
  at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:970:13)
  at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:958:20)
  at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1406:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1272:59)
  at /Users/mbroder/.atom/packages/linter/lib/linter-views.coffee:106:51
  at Array.forEach (native)
  at LinterViews.renderPanelMarkers (/Users/mbroder/.atom/packages/linter/lib/linter-views.coffee:104:11)
  at LinterViews.render (/Users/mbroder/.atom/packages/linter/lib/linter-views.coffee:42:6)
  at /Users/mbroder/.atom/packages/linter/lib/linter.coffee:30:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.updatePublic (/Users/mbroder/.atom/packages/linter/lib/message-registry.js:108:20)
  at UpdateMessages (/Users/mbroder/.atom/packages/linter/lib/message-registry.js:35:17)

```

### Commands

```
     -0:06.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:05.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:select-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tab-rename",
      "language-javascript-jsx",
      "language-jsx",
      "eslint",
      "linter-jsxhint",
      "csscomb",
      "turbo-javascript",
      "linter-jscs",
      "linter-jshint"
    ]
  },
  "linter": {
    "ignoredLinterErrors": [
      "scss-lint"
    ],
    "subtleLinterErrors": [
      "jscs"
    ],
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-color-highlight, v3.0.9
atom-handlebars, v1.1.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
css-comb, v2.1.1
docblockr, v0.7.3
editor-stats, v0.17.0
editorconfig, v1.1.0
emmet, v2.3.12
file-icons, v1.6.7
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
language-coldfusion, v0.2.1
language-ejs, v0.2.0
linter, v1.4.3
linter-coffeelint, v1.0.2
linter-csslint, v1.0.5
linter-eslint, v3.0.2
linter-htmlhint, v0.1.1
linter-less, v2.1.0
linter-ruby, v1.0.2
linter-scss-lint, v2.0.0
minimap, v4.13.1
project-manager, v1.15.11
react, v0.12.6
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Do you have a file to reproduce this with? Can you try disabling your `linter-*` packages related to JavaScript, re-enabling them one by one and seeing which causes the issue?

**Comment by steelbrain** [comment]
I am gonna have to close this one as this is a provider bug not a core linter bug, You can narrow down the provider list by the file type you were editing when you got this error.
