### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('e...

### ISSUE THREAD

**Issue by steventhanna** [atom-community/linter#872]
The following Java code triggered the error.  Please note that the code is incomplete.
```java
public class Test {

  public Test() {

  }

  public double convert(Char conv_type, double orig_length) {
    // Handle cap errors
    conv_type = conv_type.toLowerCase();
    // Create standard conversion ratio
    double ratio = 10 / 25.4;
    // 10 inches == 25.4 cm
    if(conv_type == "b") {
      // Conversion is from British to Metric
      return orig_length * ratio;
    } else if(conv_type == "m") {
      // Conversion is from Metric to British
      return orig_length / ratio;
    } else {
      // Handle error for invalid input
      System.out.println("Invalid Conversion");
      return -1;
    }
  }

  public static void main(String[] args) {
    Test test = new Test();
    System.out.println(convert('B', 10.0));
  }
}

```

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.4.3

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('error:-incompatible types') contains HTML space characters, which are not valid in tokens.

```
At /Users/steventhanna/.atom/packages/linter/lib/views/message.coffee:57

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('error:-incompatible types') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at Function.Message.renderRibbon (/Users/steventhanna/.atom/packages/linter/lib/views/message.coffee:30:18)
  at linter-message.Message.attachedCallback (/Users/steventhanna/.atom/packages/linter/lib/views/message.coffee:5:26)
  at linter-panel.<anonymous> (/Users/steventhanna/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
  at Array.forEach (native)
  at linter-panel.updateMessages (/Users/steventhanna/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
  at LinterViews.renderPanelMessages (/Users/steventhanna/.atom/packages/linter/lib/linter-views.coffee:107:12)
  at LinterViews.renderLineMessages (/Users/steventhanna/.atom/packages/linter/lib/linter-views.coffee:51:8)
  at /Users/steventhanna/.atom/packages/linter/lib/linter-plus.coffee:101:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/steventhanna/.atom/packages/linter/lib/editor-linter.coffee:14:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1610:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:346:12)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:175:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:185:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:121:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:733:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:119:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1387:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1601:9)
  at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1386:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:550:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -2:01.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  7x -1:58.9.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -1:57.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -1:55.4.0 vim-mode:change-to-last-character-of-line (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -1:54.6.0 core:undo (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:53.1.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:50 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:49.6.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:41.1.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:40.3.0 core:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:39.7.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:39 core:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:38 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:36.3.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:34.3.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:03.4.0 core:cancel (a.)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "close-tags",
      "vim-mode"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
autoclose-html, v0.18.0
bracket-matcher, v0.76.0
color-picker, v2.0.11
editor-stats, v0.17.0
language-ejs, v0.2.0
linter, v1.4.3
linter-gjslint, v0.0.5
linter-javac, v1.1.0
minimap, v4.13.2
wakatime, v4.0.16

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
I would blame `linter-javac` for providing an invalid message type.

**Comment by Arcanemagus** [comment]
To clarify, this is almost certainly a bug in `linter-javac` and you should file an issue over there with this information for the maintainers of that package to fix. Thanks for reporting the bug though!
