### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by davidesantangelo** [atom-community/linter#882]
**Atom Version**: 1.0.11
**System**: Mac OS X 10.11
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.5.1

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'emissary'

Error: Cannot find module 'emissary'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/davidesantangelo/.atom/packages/linter/node_modules/grim/lib/grim.js:4:13)
    at Object.<anonymous> (/Users/davidesantangelo/.atom/packages/linter/node_modules/grim/lib/grim.js:105:4)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ],
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.9
atom-material-ui, v0.6.0
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
color-picker, v2.0.11
emmet, v2.3.12
git-tab-status, v1.9.2
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
language-slim, v0.5.0
linter, v1.5.1
linter-ruby, v1.1.1
ruby-block, v0.3.5
set-syntax, v0.3.0
symbols-tree-view, v0.10.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
A restart should fix it.

**Comment by davidesantangelo** [comment]
No restart doesn't fix it.

**Comment by steelbrain** [comment]
Try this
```
mv ~/.atom ~/.atom-backup
apm install linter
```
and then start atom

**Comment by davidesantangelo** [comment]
it works now! Thanks.

**Comment by SSPkrolik** [comment]
@steelbrain For me this does not help

**Comment by steelbrain** [comment]
@SSPkrolik mind posting your trace?

**Comment by SSPkrolik** [comment]
@steelbrain, sure
```
/home/krolik/.atom/packages/linter/lib/ui/bottom-tab.js:3
class BottomTab extends HTMLElement{
^^^^^
Unexpected reserved word
Hide Stack Trace
/home/krolik/.atom/packages/linter/lib/ui/bottom-tab.js:3
class BottomTab extends HTMLElement{
^^^^^
SyntaxError: Unexpected reserved word
  at exports.runInThisContext (vm.js:75:16)
  at Module._compile (module.js:458:25)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/krolik/.atom/packages/linter/lib/ui/bottom-container.coffee:4:13)
  at Object.<anonymous> (/home/krolik/.atom/packages/linter/lib/ui/bottom-container.coffee:2:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/krolik/.atom/packages/linter/lib/linter-views.coffee:4:19)
  at Object.<anonymous> (/home/krolik/.atom/packages/linter/lib/linter-views.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/krolik/.atom/packages/linter/lib/linter.coffee:3:15)
  at Object.<anonymous> (/home/krolik/.atom/packages/linter/lib/linter.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.module.exports.activate (/home/krolik/.atom/packages/linter/lib/main.coffee:74:18)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:240:19)
  at /usr/share/atom/resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:461:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)
```

**Comment by steelbrain** [comment]
@SSPkrolik are you running a super-old atom?

**Comment by SSPkrolik** [comment]
@steelbrain 0.188.0

**Comment by SSPkrolik** [comment]
@steelbrain Updated to the most recent stable version, thx... Works just fine.

**Comment by Stanzilla** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.8.0


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (C:\Users\Benjamin\.atom\packages\linter\lib\main.coffee:77:15)
  at Package.module.exports.Package.activateNow (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:245:19)
  at C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:313:60
  at exit (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Benjamin\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "highlight-css-color",
      "white-cursor",
      "feedback",
      "welcome",
      "auto-indent",
      "linter-luacheck"
    ],
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false,
    "destroyEmptyPanes": false
  },
  "linter": {
    "lintOnChange": false,
    "lintOnEditorFocus": false,
    "showErrorInline": true,
    "subtleLinterErrors": [
      "php"
    ],
    "statusBar": "Show all errors",
    "showErrorTabProject": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
build, v0.47.0
build-gulp, v0.2.0
css-color-underline, v1.0.1
file-icons, v1.6.9
file-watcher, v0.4.0
fold-functions, v0.3.1
indent-guide-improved, v1.4.3
indentation-indicator, v0.6.0
keyboard-localization, v1.4.9
language-blade, v0.16.0
language-dots, v0.0.4
language-lua, v0.9.4
language-powershell, v2.1.0
laravel, v0.7.0
less-than-slash, v0.8.0
line-ending-selector, v0.0.5
linter, v1.8.0
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-php, v1.0.5
minimap, v4.13.4
open-recent, v2.3.0
revert-buffer, v0.5.0
svn, v0.0.8
tabs-to-spaces, v0.11.1
tidy-tabs, v0.3.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```
On Atom 1.0.19 when updating to Linter 1.8.0 from the previous version.

**Comment by steelbrain** [comment]
@Stanzilla just restart and you won't see that error again.

**Comment by Stanzilla** [comment]
Yep, added that info to my post, still strange :)

**Comment by steelbrain** [comment]
It's an atom update issue. Not something specific to linter.

**Comment by diegognt** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.8.1


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.module.exports.activate (/Users/diegonavarro/.atom/packages/linter/lib/main.coffee:5:5)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
```

### Commands

```
     -0:52.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-chester-atom-syntax.theme-nucleus-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "minimap-autohide",
      "language-SCSS",
      "jade-autocompile"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-styleguide-snippets, v0.7.2
atom-jade, v0.3.0
chester-atom-syntax, v0.1.1
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.13
file-icons, v1.6.9
js-refactor, v0.6.0
linter, v1.8.1
linter-htmlhint, v0.1.1
linter-jsonlint, v1.0.1
linter-php, v1.0.5
linter-scss-lint, v2.2.1
minimap, v4.13.4
minimap-git-diff, v4.1.8
nucleus-dark-ui, v0.5.13
pigments, v0.15.0
refactor, v0.6.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@davidesantangelo @Stanzilla @diegognt 
From tracking down similar issues it very much looks like this is the root issue (for Atom): https://github.com/atom/atom/issues/8891

Please follow any further news there as to when this will be fixed in Atom. Why this has suddenly started appearing in many different packages is anyone's guess...

**Comment by fungilation** [comment]
```
Error: Cannot find module 'grim'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (/Volumes/System/Users/garyfung/.atom/packages/linter/lib/main.coffee:5:5)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:313:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)
```

**Comment by steelbrain** [comment]
@fungilation See @Arcanemagus 's linked atom issue
