### ISSUE TITLE
Failed to load the linter package

### ISSUE THREAD

**Issue by NejcZdovc** [atom-community/linter#897]
Hi,

I am getting following error, when I install linter. I tried installing it on other Windows with same configuration and it's working ok.

**Atom Version**: 1.0.15
**System**: Microsoft Windows 8.1
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.6.0

### Stack Trace

Failed to load the linter package

```
At C:\Users\Admin\.atom\packages\linter\lib\main.coffee:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
Unexpected token ILLEGAL

C:\Users\Admin\.atom\packages\linter\lib\main.coffee:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:411:25)
  at Object.defineProperty.value [as .coffee] (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:761:34)
  at C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:485:30)
  at C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "background-tips",
      "image-view",
      "language-c",
      "language-clojure",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-shellscript",
      "language-source",
      "language-toml",
      "metrics",
      "timecop",
      "welcome",
      "php-twig",
      "open-on-github",
      "package-generator",
      "language-csharp",
      "language-gfm",
      "language-ruby-on-rails",
      "language-yaml",
      "linter-php"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
custom-title, v1.0.1
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.6.9
highlight-selected, v0.10.1
indent-guide-improved, v1.4.3
jquery-snippets, v11.0.0
keyboard-localization, v1.4.8
language-javascript-better, v1.5.0
language-javascript-jsx, v0.3.7
linter, v1.6.0
linter-htmlhint, v0.1.1
linter-jshint, v1.2.0
linter-xmllint, v0.0.7
minimap, v4.13.3
minimap-bookmarks, v0.1.0
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
monokai, v0.18.0
php-getters-setters, v0.5.5
project-manager, v2.5.1
Remote-FTP, v0.7.2
tasks, v2.4.0
trailing-spaces, v0.3.2
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Try this magical trick that solves nearly all of these kinda problems :D
```
mv ~/.atom ~/.atom-backup
apm install linter linter-htmlhint linter-jshint linter-xmllint
```

**Comment by Arcanemagus** [comment]
Well, on Windows the first line would be:
`mv %USERPROFILE%\.atom %USERPROFILE%\.atom-backup`
Since Windows doesn't have the `~` shortcut.

Also as a note that is just to test installation of the package to see if it's a system issue or an Atom issue.
