### ISSUE TITLE
Uncaught Error: Tried to create a gutter with a name that is already in use.

### ISSUE THREAD

**Issue by calebmeyer** [atom-community/linter#913]
[Enter steps to reproduce below:]

1. Make a vertical split using the [pain split package](https://atom.io/packages/pain-split). I specifically called `pane:split-right-moving-current-tab`

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.7.0

### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
  at TextEditor.module.exports.TextEditor.addGutter (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2613:35)
  at EditorLinter.addGutter (/Users/cm022291/.atom/packages/linter/lib/editor-linter.js:106:33)
  at EditorLinter.handleGutter (/Users/cm022291/.atom/packages/linter/lib/editor-linter.js:99:14)
  at /Users/cm022291/.atom/packages/linter/lib/editor-linter.js:50:13
  at Config.module.exports.Config.observeKeyPath (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
  at Config.module.exports.Config.observe (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at new EditorLinter (/Users/cm022291/.atom/packages/linter/lib/editor-linter.js:48:40)
  at EditorRegistry.create (/Users/cm022291/.atom/packages/linter/lib/editor-registry.coffee:13:24)
  at Linter.createEditorLinter (/Users/cm022291/.atom/packages/linter/lib/linter.coffee:80:29)
  at /Users/cm022291/.atom/packages/linter/lib/linter.coffee:36:71
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.moveItemToPane (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/pane.js:439:19)
  at atom-pane.commands.(anonymous function) (/Users/cm022291/.atom/packages/pain-split/lib/pain-split.coffee:31:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/1.0.10/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -1:56.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:54.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:50 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:47.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:47.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:45.4.0 pane:show-previous-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:44.4.0 pane:show-next-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:43.6.0 pane:show-previous-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:43.1.0 pane:show-next-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 40x -1:41.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 32x -1:39.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 29x -1:33.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  5x -1:28.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:09.6.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:56 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 pane:split-right-moving-current-tab (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-mustache",
      "linter-haml",
      "deprecation-cop",
      "overrides",
      "autocomplete-paths",
      "linter-foodcritic",
      "linter-less",
      "line-ending-selector"
    ],
    "themes": [
      "accents-ui",
      "photon-syntax"
    ]
  },
  "linter": {
    "statusBar": "Show error of the selected line",
    "clearOnChange": true,
    "lintOnChange": false,
    "ignoredLinterErrors": [
      "foodcritic"
    ],
    "lintOnFly": false
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.0.0
atom-jasmine, v0.6.0
auto-update-packages, v1.0.0
file-icons, v1.6.9
highlight-line, v0.11.0
language-diff, v0.3.1
language-gitignore, v0.2.0
language-haml, v0.22.2
language-lisp, v0.1.2
language-log, v0.6.0
language-restructuredtext, v0.9.0
language-rspec, v0.3.0
language-rust, v0.4.5
linter, v1.7.0
minimap, v4.13.4
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
omni-ruler, v0.4.2
open-recent, v2.3.0
pain-split, v1.4.0
photon-syntax, v0.4.8
set-syntax, v0.3.0
trailing-spaces, v0.3.2
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by austincummings** [comment]
:+1:

**Comment by steelbrain** [comment]
Restart the editor and it should be fixed

**Comment by steelbrain** [comment]
I am afraid it's a problem with the way that package handles panes, the builtin `pane:*` work fine. Please open an issue over to their repo :)

**Comment by seronal** [comment]
I just got this error, and I don't have that package.

1. Move a tab from one pane to another.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.7.2


### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
  at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2613:35)
  at EditorLinter.addGutter (/Users/Serdar/.atom/packages/linter/lib/editor-linter.js:106:33)
  at EditorLinter.handleGutter (/Users/Serdar/.atom/packages/linter/lib/editor-linter.js:99:14)
  at /Users/Serdar/.atom/packages/linter/lib/editor-linter.js:50:13
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at new EditorLinter (/Users/Serdar/.atom/packages/linter/lib/editor-linter.js:48:40)
  at EditorRegistry.create (/Users/Serdar/.atom/packages/linter/lib/editor-registry.coffee:13:24)
  at Linter.createEditorLinter (/Users/Serdar/.atom/packages/linter/lib/linter.coffee:80:29)
  at /Users/Serdar/.atom/packages/linter/lib/linter.coffee:36:71
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:439:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:706:20)
  at TabBarView.module.exports.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:632:23)
  at space-pen-ul.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -5:37.9.0 core:save (atom-text-editor.editor.is-focused)
     -5:20.5.0 core:copy (atom-text-editor.editor.is-focused)
     -5:20.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  8x -5:19.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:16 core:backspace (atom-text-editor.editor.is-focused)
     -5:15.3.0 core:save (atom-text-editor.editor.is-focused)
     -5:12.3.0 core:cut (atom-text-editor.editor.is-focused)
  2x -5:11.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:09.5.0 core:paste (atom-text-editor.editor.is-focused)
     -5:09.1.0 core:save (atom-text-editor.editor.is-focused)
     -4:25.3.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -4:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:18.9.0 core:paste (atom-text-editor.editor.is-focused)
     -4:18.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.3.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tool-bar-main"
    ],
    "themes": [
      "one-dark-ui",
      "outlander-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.14
atom-jasmine, v0.6.0
atom-ternjs, v0.8.1
color-picker, v2.0.12
file-icons, v1.6.9
language-lua, v0.9.4
linter, v1.7.2
linter-jscs, v3.0.0
linter-jshint, v1.2.0
minimap, v4.13.4
outlander-syntax, v1.0.3
pigments, v0.15.0
save-session, v0.15.7
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
I think that's an issue with atom itself. Ref: https://github.com/atom/atom/issues/9012

**Comment by rohanray** [comment]
Facing same issue. Details: https://github.com/atom/atom/issues/9012#issuecomment-144640545

**Comment by jadatkins** [comment]
I've got it too. Just started today. [Here's my log](https://github.com/atom/atom/issues/9012#issuecomment-144767782).

**Comment by jonathanong** [comment]
:+1:

**Comment by steelbrain** [comment]
@jonathanong you might wanna +1 it on that atom issue.

**Comment by PCateNumbersUSA** [comment]
Started getting this with the last atom.io update a day or so ago.

**Comment by steelbrain** [comment]
@PCateNumbersUSA See atom/atom#9012

**Comment by timhyson** [comment]
+1.

**Comment by yriveiro** [comment]
+1

**Comment by steelbrain** [comment]
Guys `+1`ing here won't be helpful in **any** way, this isn't a linter issue, `+1` the linked atom issue.
