### ISSUE TITLE
I get this error for every keystroke I make in atom

### ISSUE THREAD

**Issue by seekshiva** [atom-community/linter#981]
I get this error for every keystroke I make in atom

```
Error: Got both html and text fields on Linter Response, expecting only one
  at /Users/shiva/.atom/packages/linter/lib/validate.coffee:33:19
  at Array.forEach (native)
  at Object.module.exports.Validate.messages (/Users/shiva/.atom/packages/linter/lib/validate.coffee:26:14)
  at MessageRegistry.set (/Users/shiva/.atom/packages/linter/lib/message-registry.js:56:18)
  at /Users/shiva/.atom/packages/linter/lib/linter.coffee:27:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /Users/shiva/.atom/packages/linter/lib/linter-registry.js:98:29
```

**Comment by steelbrain** [comment]
Oops, forgot to publish a `linter-eslint` release after the change.
It's a provider bug not this linter's bug, but I manage that repo too, so will fix it

**Comment by steelbrain** [comment]
The fix is in latest `linter-eslint`. Upgrade it.
