### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by elinnet** [atom-community/linter#983]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.10.0

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (/Users/elinnet/.atom/packages/linter/lib/main.coffee:76:5)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
  3x -1:03.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:03.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:59.2.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -0:57.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:32.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:05.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:03.6.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-eslint",
      "autoclose-html"
    ],
    "destroyEmptyPanes": false
  },
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
indent-guide-improved, v1.4.3
linter, v1.10.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Please restart Atom and see if you are still seeing this issue.

**Comment by jnials** [comment]
Problem went away for me after an update.

**Comment by Arcanemagus** [comment]
This is an issue with the old version of Electron that Atom v1.1.0 (and older) ships with, it _should_ be fixed in v1.2.0 and above.

**Comment by andreykko** [comment]
Same on win10

**Comment by CaptainBland** [comment]
Yep, just had this issue on Ubuntu 14.04. Maybe this suggests I should upgrade more frequently.

**Comment by Arcanemagus** [comment]
We've seen reports from all OS's for a while now, like I said this won't be fixed until v.1.2.0 gets released. Luckily a simple restart fixes this issue, there is a related issue with non-ASCII profile paths that make most plugins break for anyone not using v1.2.0.

**Comment by steelbrain** [comment]
Duplicated of https://github.com/atom-community/linter/issues/942 and https://github.com/atom-community/linter/issues/882
