### ISSUE TITLE
Uncaught Error: spawn pep8 ENOENT

### ISSUE THREAD

**Issue by jdhunterae** [atom-community/linter#984]
When launched, either from GUI or command line atom opens with notification errors indicating:

    Error: write EPIPE
        at exports._errnoException (util.js:814:11)
        at Socket._writeGeneric (net.js:672:26)
        at Socket._write (net.js:691:8)
        at doWrite (_stream_writable.js:291:12)
        at writeOrBuffer (_stream_writable.js:277:5)
        at Socket.Writable.write (_stream_writable.js:206:11)
        at Socket.write (net.js:615:40)
        at C:\Users\andrew.pomerleau\.atom\packages\linter-pep8\node_modules\atom-linter\lib\helpers.coffee:22:30
        at Object.module.exports.Helpers.exec (C:\Users\andrew.pomerleau\.atom\packages\linter-pep8\node_modules\atom-linter\lib\helpers.coffee:14:16)
        at Object.provider.lint (C:\Users\andrew.pomerleau\.atom\packages\linter-pep8\lib\main.coffee:30:24)

and also:

    'pep8' could not be spawned. Is it installed and on your path?
    If so please open an issue on the package spawning the process.

while the window opens the side-pane instance of console saying:

    Loading /C:/Users/andrew.pomerleau/.atom/packages/emmet/lib/emmet.coffee:133
    Emmet extensions from ~/emmet
    Emmet: /C:/Users/andrew.pomerleau/.atom/packages/emmet/lib/emmet.coffee:150
    no such extension folder: C:\Users\andrew.pomerleau/emmet
    /C:/Users/andrew.pomerleau/.atom/packages/linter-htmlhint/lib/init.coffee:18
    activate linter-htmlhint
    Window load time: 1199ms                                       index.js:46
    Uncaught Error: spawn pep8 ENOENT	                         events.js:141

**Comment by Arcanemagus** [comment]
This is most likely an issue of misconfiguration of the [linter-pep8](https://github.com/AtomLinter/linter-pep8) package.

**Comment by steelbrain** [comment]
Closing based on comment above. This issue belongs to `linter-pep8`. Even then the error says it all ENOENT means the file you specified as executable wasn't found.
