### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by cawparky** [atom-community/linter#989]
After install fedora and atom linter always show this message. (I tried to reinstall atom, npm, gcc few times with no result).

object is not a function

TypeError: object is not a function
  at Object.module.exports.activate (/home/majko/.atom/packages/linter/lib/main.coffee:131:21)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:232:19)
  at /usr/share/atom/resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:153:15)
  at /usr/share/atom/resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:474:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

**Comment by steelbrain** [comment]
Can you please restart your editor and see if it's activating then?

**Comment by cawparky** [comment]
nop i tried to restart atom many times ..

**Comment by steelbrain** [comment]
Step 1: Close Atom
Step 2: Execute this in a terminal
```
mv ~/.atom ~/.atom-backup
apm install linter
```
Step 3: Start atom

^ Can you try that and confirm if it works?

**Comment by cawparky** [comment]
it works! thanks so much :)

**Comment by steelbrain** [comment]
I am glad it does :)
Here's a version that will restore your config and most likely make it work again
```bash
mv ~/.atom /tmp/atom-config-used # To remove the .atom folder that was creating during this experiment
mv ~/.atom-backup ~/.atom # To restore the backup .atom folder
apm uninstall linter
apm install linter
```
