### ISSUE TITLE
Error when typing

### ISSUE THREAD

**Issue by rugk** [atom-community/linter#993]
I just wrote a simple markdown file and when I was (vertically) near the end of the screen/browser window these error popped up two times. Every

```
Error: Got both html and text fields on Linter Response, expecting only one
  at D:\Users\%username%\.atom\packages\linter\lib\validate.coffee:33:19
  at Array.forEach (native)
  at Object.module.exports.Validate.messages (D:\Users\%username%\.atom\packages\linter\lib\validate.coffee:26:14)
  at MessageRegistry.set (D:\Users\%username%\.atom\packages\linter\lib\message-registry.js:56:18)
  at D:\Users\%username%\.atom\packages\linter\lib\linter.coffee:27:17
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at D:\Users\%username%\.atom\packages\linter\lib\linter-registry.js:98:29
```

Installed linter packages:
* linter 1.10.0
* linter-alex 1.5.0
* linter-htmlhint 0.2.1
* linter-php 1.1.0

**Comment by steelbrain** [comment]
Can you tell us which type of file were you editing when you got this error? It'll help us pinpoint the provider.

**Comment by rugk** [comment]
Markdown file like I said.
But I already got it out by disabling the linter packages one by one.

So moving this issue: https://github.com/wooorm/atom-linter-alex/issues/11
